<a href="https://colab.research.google.com/github/AKHILM20DS007/AKHILM20DS007/blob/main/18th_Oct_Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("We are learning Numpy")  ## press shift + enter

We are learning Numpy


In [ ]:
import numpy as np

In [ ]:
### Create an array using Numpy
### Array - Collection of homogenous(similar) data

In [ ]:
data = [1,4,56,3,6,4,6,4]
a1 = np.array(data)   ## 1d array
a1

array([ 1,  4, 56,  3,  6,  4,  6,  4])

In [ ]:
a1 = np.array([1,4,56,3,6,4,6,4])   ## 1d array
a2 = np.array([[1,4,56,3,6,4,6,4]])  ## 2d array
a3 = np.array([[1,4,56,3,6,4,6,4],
               [16,4,556,35,65,45,65,45],
               [1,44,546,43,64,4,64,44],
               [31,434,5436,433,634,34,3643,344]])  ## 2d array
a4 = np.array([[[1,4,56,3,6,4,6,4],
               [16,4,556,35,65,45,65,45],
               [1,44,546,43,64,4,64,44],
               [31,434,5436,433,634,34,3643,344]]])  ## 3d array
a5 = np.array([[[1,4,56,3,6,4,6,4],
               [16,4,556,35,65,45,65,45],
               [1,44,546,43,64,4,64,44],
               [31,434,5436,433,634,34,3643,344]],
               
               [[1,4,56,3,6,4,6,4],
               [16,4,556,35,65,45,65,45],
               [1,44,546,43,64,4,64,44],
               [31,434,5436,433,634,34,3643,344]]]) ### 3d array

In [ ]:
a1

array([ 1,  4, 56,  3,  6,  4,  6,  4])

In [ ]:
a2

array([[ 1,  4, 56,  3,  6,  4,  6,  4]])

In [ ]:
a3

array([[   1,    4,   56,    3,    6,    4,    6,    4],
       [  16,    4,  556,   35,   65,   45,   65,   45],
       [   1,   44,  546,   43,   64,    4,   64,   44],
       [  31,  434, 5436,  433,  634,   34, 3643,  344]])

In [ ]:
a4

array([[[   1,    4,   56,    3,    6,    4,    6,    4],
        [  16,    4,  556,   35,   65,   45,   65,   45],
        [   1,   44,  546,   43,   64,    4,   64,   44],
        [  31,  434, 5436,  433,  634,   34, 3643,  344]]])

In [ ]:
a5

array([[[   1,    4,   56,    3,    6,    4,    6,    4],
        [  16,    4,  556,   35,   65,   45,   65,   45],
        [   1,   44,  546,   43,   64,    4,   64,   44],
        [  31,  434, 5436,  433,  634,   34, 3643,  344]],

       [[   1,    4,   56,    3,    6,    4,    6,    4],
        [  16,    4,  556,   35,   65,   45,   65,   45],
        [   1,   44,  546,   43,   64,    4,   64,   44],
        [  31,  434, 5436,  433,  634,   34, 3643,  344]]])

In [ ]:
print(len(a1))
print(len(a2))
print(len(a3))
print(len(a4))
print(len(a5))

8
1
4
1
2


In [ ]:
print(a1.shape)
print(a2.shape)  ### 1 1d array of shape (8)
print(a3.shape)  ### 4 1d array of shape (8)
print(a4.shape)  ### 1 2d array of shape (4,8)
print(a5.shape)  ### 2 2d array of shapee (4,8)

(8,)
(1, 8)
(4, 8)
(1, 4, 8)
(2, 4, 8)


In [ ]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)
print(a4.dtype)
print(a5.dtype)

int64
int64
int64
int64
int64


In [ ]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
print(a4.ndim)
print(a5.ndim)

1
2
2
3
3


In [ ]:
### Slicing of Array

In [ ]:
a3

array([[   1,    4,   56,    3,    6,    4,    6,    4],
       [  16,    4,  556,   35,   65,   45,   65,   45],
       [   1,   44,  546,   43,   64,    4,   64,   44],
       [  31,  434, 5436,  433,  634,   34, 3643,  344]])

In [ ]:
a3[:,:]    # row,column

array([[   1,    4,   56,    3,    6,    4,    6,    4],
       [  16,    4,  556,   35,   65,   45,   65,   45],
       [   1,   44,  546,   43,   64,    4,   64,   44],
       [  31,  434, 5436,  433,  634,   34, 3643,  344]])

In [ ]:
a3[2]

array([  1,  44, 546,  43,  64,   4,  64,  44])

In [ ]:
a3[1:3,:]

array([[ 16,   4, 556,  35,  65,  45,  65,  45],
       [  1,  44, 546,  43,  64,   4,  64,  44]])

In [ ]:
a3[1:,:]

array([[  16,    4,  556,   35,   65,   45,   65,   45],
       [   1,   44,  546,   43,   64,    4,   64,   44],
       [  31,  434, 5436,  433,  634,   34, 3643,  344]])

In [ ]:
a3[:3,:]

array([[  1,   4,  56,   3,   6,   4,   6,   4],
       [ 16,   4, 556,  35,  65,  45,  65,  45],
       [  1,  44, 546,  43,  64,   4,  64,  44]])

In [ ]:
a3[1:3,2:5]

array([[556,  35,  65],
       [546,  43,  64]])

In [ ]:
#### Array Functions

In [ ]:
a3

array([[   1,    4,   56,    3,    6,    4,    6,    4],
       [  16,    4,  556,   35,   65,   45,   65,   45],
       [   1,   44,  546,   43,   64,    4,   64,   44],
       [  31,  434, 5436,  433,  634,   34, 3643,  344]])

In [ ]:
a3.sum()

12714

In [ ]:
a3.sum(axis=0)

array([  49,  486, 6594,  514,  769,   87, 3778,  437])

In [ ]:
a3.sum(axis=1)

array([   84,   831,   810, 10989])

In [ ]:
a3.mean()

397.3125

In [ ]:
a3.max()

5436

In [ ]:
a3.min()

1

In [ ]:
a3

array([[   1,    4,   56,    3,    6,    4,    6,    4],
       [  16,    4,  556,   35,   65,   45,   65,   45],
       [   1,   44,  546,   43,   64,    4,   64,   44],
       [  31,  434, 5436,  433,  634,   34, 3643,  344]])

In [ ]:
a3.argmax()

26

In [ ]:
a3.argmin()

0

In [ ]:
a3

array([[   1,    4,   56,    3,    6,    4,    6,    4],
       [  16,    4,  556,   35,   65,   45,   65,   45],
       [   1,   44,  546,   43,   64,    4,   64,   44],
       [  31,  434, 5436,  433,  634,   34, 3643,  344]])

In [ ]:
a3.shape

(4, 8)

In [ ]:
a3_1 = a3.reshape(32)
a3_1

In [ ]:
a3_2 = a3.reshape(2,16)   ## 8,4  2,16  16,2  32,1   1,32
a3_2

In [ ]:
a3_3 = a3.reshape(2,4,4)
a3_3

In [ ]:
a3

In [ ]:
a3.argmax()

26

In [ ]:
a3_1[26]

5436

In [ ]:
### Random Function

In [ ]:
np.random.randint(100)  ## any random number between 0 to 99

In [ ]:
np.random.seed(10)    ## any value b/w 0 to 2**32 - 1
np.random.randint(100)

9

In [ ]:
np.random.randint(100,1000)  ## any random number between 100 to 999

In [ ]:
np.random.randint(100,1000,10)

In [ ]:
np.random.randint(100,1000,(5,4))

array([[140, 602, 520, 471],
       [628, 456, 339, 495],
       [154, 444, 463, 222],
       [674, 645, 300, 968],
       [789, 791, 154, 177]])

In [ ]:
### Standard Matrices

In [ ]:
np.zeros((4,5),np.int32)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [ ]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])